version: "3.9"

services:
  hardhat-node:
    container_name: hardhat-node
    build:
      context: ..
      dockerfile: docker/hardhat.Dockerfile
    restart: always
    ports:
      - 8545:8545
    command: npm run start:hardhat:node
  hardhat-deploy:
    container_name: hardhat-deploy
    build:
      context: ..
      dockerfile: docker/hardhat.Dockerfile
    volumes:
      - ../packages/hardhat/deployments:/src/packages/hardhat/deployments
    command: npm run start:hardhat:deploy:docker
    depends_on:
      - hardhat-node
  ipfs:
    image: ipfs/go-ipfs:master-latest
    container_name: ipfs
    ports:
      - 5001:5001
    volumes:
      - ./data/ipfs:/data/ipfs
  dapp:
    container_name: dapp
    build:
      context: ..
      dockerfile: docker/dapp.Dockerfile
    volumes:
      - ../packages/dapp:/src/packages/dapp
      - ../packages/hardhat/deployments:/src/packages/hardhat/deployments
      - /src/node_modules
      - /src/packages/dapp/node_modules
      - /src/packages/dapp/.next
    ports:
      - 3000:3000
    env_file:
      - ../packages/dapp/.env.local
    command: npm run start:dapp
    depends_on:
      - hardhat-node
      - hardhat-deploy
      - ipfs
