version: "3.9"

services:
  hardhat-node:
    build:
      context: ..
      dockerfile: docker/hardhat.Dockerfile
    restart: always
    ports:
      - 8545:8545
    command: npm run start:hardhat:node -w @ethernauts/hardhat

  hardhat-deploy:
    build:
      context: ..
      dockerfile: docker/hardhat.Dockerfile
    volumes:
      - ../packages/hardhat/deployments:/src/packages/hardhat/deployments
      - ../packages/hardhat/artifacts:/src/packages/hardhat/artifacts
      - ../packages/hardhat/cache:/src/packages/hardhat/cache
    command: sh -c "/wait && rm ./packages/hardhat/deployments/docker.json && npm run start:hardhat:compile -w @ethernauts/hardhat && npm run start:hardhat:deploy:docker -w @ethernauts/hardhat"
    environment:
      WAIT_HOSTS: hardhat-node:8545
    depends_on:
      - hardhat-node

  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - 5001:5001
    volumes:
      - ./data/ipfs:/data/ipfs

  redis:
    image: redis:6.2-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

  keeper-queue:
    build:
      context: ..
      dockerfile: docker/keeper.Dockerfile
    restart: always
    command: sh -c "/wait && npm run -w @ethernauts/keeper queue -- --network docker"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      WAIT_HOSTS: hardhat-node:8545
    volumes:
      - ../packages/keeper:/src/packages/keeper
      - ../packages/hardhat/deployments:/src/packages/hardhat/deployments
      - /src/node_modules
      - /src/packages/keeper/node_modules
    depends_on:
      - hardhat-node
      - hardhat-deploy
      - ipfs
      - redis

  dapp:
    build:
      context: ..
      dockerfile: docker/dapp.Dockerfile
    volumes:
      - ../packages/dapp:/src/packages/dapp
      - ../packages/hardhat/artifacts:/src/packages/hardhat/artifacts
      - ../packages/hardhat/deployments:/src/packages/hardhat/deployments
      - /src/node_modules
      - /src/packages/dapp/node_modules
      - /src/packages/dapp/.next
    ports:
      - 3000:3000
    env_file:
      - ../packages/dapp/.env.local
    command: sh -c "/wait && npm run start:dapp"
    environment:
      WAIT_HOSTS: hardhat-node:8545
    depends_on:
      - hardhat-node
      - hardhat-deploy
      - ipfs
