version: "3.9"

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - ${REDIS_FOLDER}:/data

  keeper-queue:
    build:
      context: https://github.com/ethernautdao/ethernauts.git#${BRANCH:-main}
      dockerfile: docker/keeper.production.Dockerfile
    command: npm run -w @ethernauts/keeper errors-report && npm run -w @ethernauts/keeper queue -- --no-compile --network ${NETWORK}
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always
    depends_on:
      - redis

  keeper-worker:
    build:
      context: https://github.com/ethernautdao/ethernauts.git#${BRANCH:-main}
      dockerfile: docker/keeper.production.Dockerfile
    command: npm run -w @ethernauts/keeper errors-report && npm run -w @ethernauts/keeper worker -- --no-compile --network ${NETWORK}
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RESOURCES_METADATA_FOLDER: /src/resources/metadata
      RESOURCES_ASSETS_FOLDER: /src/resources/assets
    volumes:
      - ${RESOURCES_METADATA_FOLDER}:/src/resources/metadata:ro
      - ${RESOURCES_ASSETS_FOLDER}:/src/resources/assets:ro
    restart: always
    depends_on:
      - redis
