name: CI

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ] 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 14 LTS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Installing dependencies
        run: npm install
      
      - name: Running Linters
        run: npm run lint

      - name: Running Tests
        run: npm run coverage