name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Installing dependencies
        run: npm ci

      - name: Create env file
              run: |
                touch .env
                echo DEPLOYER_KEY="95e3fe10f5d1d8a3fc7971a5cc65776ae80453f354f17f61a714fb8f9790b915" >> .env
                echo ETHERSCAN_API=dsadsae44sadsadsa >> .env
                cat .env
                
      - name: Running Linters
        run: npm run lint

      - name: Running Tests
        run: npm run coverage
