name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 14 LTS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Installing dependencies
        run: npm install
      
      - name: Running Linters
        run: npm run lint:fix
      
      - name: Checking Linters
        run: npm run lint
      
      - name: Running Tests
        run: npm run test

      - name: Running Coverage
        run: npm run coverage

