name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Installing dependencies
        run: npm ci

      - name: Running Linters
        run: npm run lint

      - name: Running Tests
        run: npm run coverage
